openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8082
    description: Generated server url
paths:
  /company:
    post:
      tags:
        - company-api
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCompanyRequest'
        required: true
      responses:
        '200':
          description: Company has been created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CompanyResponse'
        '400':
          description: Bad request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CompanyResponse'
  /company/{companyId}:
    get:
      tags:
        - company-api
      summary: Find company by ID
      description: The endpoint for retrieving the company
      operationId: findCompanyById
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CompanyResponse'
        '404':
          description: Currency not found
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CompanyResponse'
components:
  schemas:
    CreateCompanyRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the social media company
          minLength: 1
        country:
          type: string
          description: The name of the country where the social media company is located
        currencyId:
          type: string
          format: uuid
          description: The currency that the social media company uses by default
    CompanyResponse:
      type: object
      properties:
        companyId:
          type: string
          format: uuid
          description: The currency that the social media company uses by default
        name:
          type: string
          description: The name of the social media company
        country:
          type: string
          description: The name of the country where the social media company is located
        currencyId:
          type: string
          format: uuid
          description: The currency that the social media company uses by default
