openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8083
    description: Generated server url
paths:
  /customer/{customerId}:
    get:
      tags:
        - customer-api
      operationId: findCustomerById
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomerResponse'
    put:
      tags:
        - customer-api
      operationId: updateCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomerResponse'
    delete:
      tags:
        - customer-api
      operationId: deleteCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
  /customer:
    get:
      tags:
        - customer-api
      operationId: getCustomersFromCompany
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FindCustomersResponse'
    post:
      tags:
        - customer-api
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CustomerResponse'
components:
  schemas:
    CustomerRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        taxIdentificationNumber:
          type: string
        taxIdentificationType:
          type: string
        taxRegime:
          type: string
        annualRevenue:
          type: number
          format: double
        country:
          type: string
        address:
          type: string
        postalCode:
          type: string
        businessSector:
          type: string
        establishmentDate:
          type: string
          format: date
        notes:
          type: string
        currencyId:
          type: string
          format: uuid
    CustomerResponse:
      type: object
      properties:
        customerId:
          type: string
          format: uuid
        name:
          type: string
        taxIdentificationNumber:
          type: string
        taxIdentificationType:
          type: string
        taxRegime:
          type: string
        annualRevenue:
          type: number
          format: double
        country:
          type: string
        address:
          type: string
        postalCode:
          type: string
        businessSector:
          type: string
        establishmentDate:
          type: string
          format: date
        notes:
          type: string
        currencyId:
          type: string
          format: uuid
    FindCustomersResponse:
      type: object
      properties:
        customers:
          type: array
          items:
            $ref: '#/components/schemas/CustomerResponse'
